### ISSUE TITLE
PineTime: Timeout and reset on DFU

### ISSUE THREAD

**Issue by flacks** [daniel-thompson/wasp-reloader#2]
On PineTime, with 7b0905b9d36d9fb9fae5e8ae1f4ad0c536904110, when trying to send anything with DFU using nRF Connect, PineTime immediately resets on upload, making DFU impossible. Current solution is to reflash another bootloader via SWD. Working on bisecting this. Thank you for your efforts!

![pinetime_reloader_7b0905b9](https://user-images.githubusercontent.com/2135469/99217324-cdc10c00-27a5-11eb-9031-c22d59e82f8a.png)

**Comment by flacks** [comment]
Ack. Removing a Bluetooth-based COVID-19 app from my Android device and cycling Bluetooth resulted in DFU working properly with latest (mentioned) reloader, to where I was able to flash wasp-os (micropython.zip). I suspect the COVID-19 app being the culprit, because DFU would always fail with latest reloader as well as 0.2 (M2) release binaries, with both nRF Connect as well as DaFlasher. Closing.

**Comment by micah-rufsvold** [comment]
I wanted to flag that I am getting the exact same behavior after having uninstalled my covid app, cycling BT, and rebooting my phone. Also errors with DaFlasher. Any thoughts on other troubleshooting steps?

**Comment by micah-rufsvold** [comment]
For those brought here by the internet in the future -- I solved this by going to nRF Connect >Settings> DFU Options and setting Packet number to 5.
